# Generated by Django 3.1.7 on 2021-04-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20210415_0031'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='media',
        ),
    ]
