# Generated by Django 3.1.7 on 2021-04-14 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_auto_20210415_0105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='media',
            new_name='Product',
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
